// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Logs.Models;

public partial class AccidentesContext : DbContext
{
    public AccidentesContext(DbContextOptions<AccidentesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblAccidente> TblAccidentes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TblAccidente>(entity =>
        {
            entity.ToTable("tblAccidentes");

            entity.Property(e => e.Ciudad).IsRequired();
            entity.Property(e => e.Descripcion).IsRequired();
            entity.Property(e => e.FechaAccidente).HasColumnType("datetime");
            entity.Property(e => e.Geolocalizacion).IsRequired();
            entity.Property(e => e.Pais).IsRequired();
            entity.Property(e => e.Usuario).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}