// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Logs.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Logs.Models
{
    public partial class AccidentesContext
    {
        private IAccidentesContextProcedures _procedures;

        public virtual IAccidentesContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AccidentesContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IAccidentesContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class AccidentesContextProcedures : IAccidentesContextProcedures
    {
        private readonly AccidentesContext _context;

        public AccidentesContextProcedures(AccidentesContext context)
        {
            _context = context;
        }

        public virtual async Task<int> INSERTACCIDENTEAsync(string desc, int? heridos, int? fallecidos, int? veh, DateTime? fecha, int? estado, string geo, string usuario, string ciudad, string pais, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Desc",
                    Size = -1,
                    Value = desc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Heridos",
                    Value = heridos ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Fallecidos",
                    Value = fallecidos ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Veh",
                    Value = veh ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Fecha",
                    Value = fecha ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "Estado",
                    Value = estado ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Geo",
                    Size = -1,
                    Value = geo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Usuario",
                    Size = -1,
                    Value = usuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Ciudad",
                    Size = -1,
                    Value = ciudad ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Pais",
                    Size = -1,
                    Value = pais ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[INSERTACCIDENTE] @Desc = @Desc, @Heridos = @Heridos, @Fallecidos = @Fallecidos, @Veh = @Veh, @Fecha = @Fecha, @Estado = @Estado, @Geo = @Geo, @Usuario = @Usuario, @Ciudad = @Ciudad, @Pais = @Pais", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
