// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Logs.Models;

public partial class TblAccidente
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public int CantidadHeridos { get; set; }

    public int CantidadFallecidos { get; set; }

    public int CantidadVehiculos { get; set; }

    public DateTime FechaAccidente { get; set; }

    public int EstadoRegistro { get; set; }

    public string Geolocalizacion { get; set; }

    public string Usuario { get; set; }

    public string Ciudad { get; set; }

    public string Pais { get; set; }
}